/* Icon is found in main ts component
*  icon from svg in assets folder
*/
export enum EntityIcon {
  dqHomeRe1 = 'dqhome.re1',
  dqHomeRe2 = 'dqhome.re2',
  dqHomeRe3 = 'dqhome.re3',
  dqHomeRe4 = 'dqhome.re4',
  dqHomeRe6 = 'dqhome.re6',
  lumiRemoteB1acn01 = 'lumi.remote.b1acn01',
  lumiRemoteB286acn01 = 'lumi.remote.b286acn01',
  lumiSensorMotionAq2 = 'lumi.sensor_motion.aq2',
  lumiSensorWleakAq1 = 'lumi.sensor_wleak.aq1',
  lumiVivrationAq1 = 'lumi.vibration.aq1',
  lumiWeather = 'lumi.weather',
  automation = 'automation',
  tubeLight = 'tube-light',
  temperature = 'temperature',
  motionSensor = 'motion-sensor',
  lightBulbV2 = 'light-bulb-v2',
  bulbLightRgbV4 = 'bulb-light-rgb-v4',
  iotMotionSensor = 'iot-motion-sensor',
  bluetooth = 'bluetooth',
  wifi = 'wifi',
  zigbee = 'zigbee',
  lorawan = 'lorawan',
  energySensor = 'power',
  tubeLightRadar2in1 = 'bulb-radar',
  bulbLight = 'bulb-light',
  spotLight = 'spot-light',
  stripLight = 'strip-light',
  lightUnknown = 'light-unknown',
  deviceUnknown = 'device-unknown',
  gatewayV1 = 'gateway_v1',
  hubV1 = 'hub_v1',
  rgbControl = 'rgb-control',
  humidity = 'humidity',
  iotLight = 'iot-light',
  smartButton = 'smart-button',
  waterSensor = 'water-sensor',
  iotScene = 'iot-scene',
  mapView = 'map-view',
  airConditioner = 'air-conditioner',
  curtains = 'curtains',
  curtainsClosed = 'curtains-closed',
  mediaPlayer = 'media-player',
  iotGroupLight = 'iot-group-light',
  iotGroupScene = 'iot-group-scene',
  iotBinaryInput = 'iot-binary-input',
  iotMotionBinaryInput = 'iot-motion-binary-input',
  iotSmokeBinaryInput = 'iot-smoke-binary-input',
  iotCommonSensor = 'iot-common-sensor',
  iotLightSwitch = 'iot-light-switch',
  displayMatrix = 'display-matrix',
  rfId = 'rfid'
}

/*export enum EntityIconEnumUrl {
  bulbLight = './assets/apollo/icon/bulb-light.svg',
  bulbLightRgb = './assets/apollo/icon/bulb-light-rgb-v2.svg',
  bulbLight2In1 = './assets/apollo/icon/bulb-radar-2-in-1',
  tubeLight = './assets/apollo/icon/tube-light',
  spotLight = './assets/apollo/icon/spot-light',
  stripLight = './assets/apollo/icon/strip-light',
  unknownLight = './assets/apollo/icon/light-unknown.svg',
  unknownDevice = './assets/apollo/icon/device-unknown.svg',
  motionSensor = './assets/apollo/icon/motion-sensor.svg',
  energySensor = './assets/apollo/icon/power',
  temperatureSensor = './assets/apollo/icon/temperature_sensor',
  airConditioner = './assets/apollo/icon/air-conditioner.svg',
  automation = './assets/apollo/icon/automation.svg'
}*/
