export enum PageView {
  MAP = 'MAP',
  SCHEDULER = 'SCHEDULER',
  AUTOMATION = 'AUTOMATION',
  ANALYZE = 'ANALYZE',
  NORMAL = 'NORMAL'
}


export enum EventTask {
  DELETE_ENTITIES = 'DELETE_ENTITIES',
  ADD_ENTITY = 'ADD_ENTITY',
  EDIT_ENABLE = 'EDIT_ENABLE',
  ENTER_MAP_VIEWER = 'ENTER_MAP_VIEWER',
  ENTER_SCHEDULER_VIEWER = 'ENTER_SCHEDULER_VIEWER',
  ENTER_AUTOMATION_VIEWER = 'ENTER_AUTOMATION_VIEWER',
  PREVIOUS_PARENT_ENTITY = 'PREVIOUS_PARENT_ENTITY',
  NEXT_PARENT_ENTITY = 'NEXT_PARENT_ENTITY',
  HOME_PAGE = 'HOME_PAGE',
  ANALYZE_VIEWER = 'ANALYZE_VIEWER',
  RELOAD_ENITY = 'RELOAD_ENITY',
  WIDGET_SETTING = 'WIDGET_SETTING',
  SAVE_DATABASE = 'SAVE_DATABASE',
  REQUEST_UPDATE_NEW_STATE='REQUEST_UPDATE_NEW_STATE'

}
